### ISSUE TITLE
SLADE 3.2.0 fails to build on arch linux

### ISSUE THREAD

**Issue by Doommsatic** [sirjuddington/SLADE#1336]
**SLADE Version**: 3.2.0
**Operating System**: Arch Linux

Compiling on Arch fails with this error:
```
SLADE/src/Graphics/Icons.cpp: In function ‘bool slade::icons::loadIcons()’:
SLADE/src/Graphics/Icons.cpp:376:43: error: ‘GetAppearance’ is not a member of ‘wxSystemSettings’
  376 |         ui_icons_dark = wxSystemSettings::GetAppearance().IsDark();
      |                                           ^~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/slade.dir/build.make:1051: src/CMakeFiles/slade.dir/Graphics/Icons.cpp.o] Error 1
```
I ran git bisect and it compiles without any issues before commit https://github.com/sirjuddington/SLADE/commit/3683bc76be61dbb85a407e2df628ad1796242a90
