### ISSUE TITLE
Linux compile fails (again) with NO_WEBVIEW set to ON

### ISSUE THREAD

**Issue by saski4711** [sirjuddington/SLADE#741]
SLADE Version: current git
Operating System: Gentoo Linux

Issue Details:

This was fixed with Issue #730 for some days and then it was broken again :(

Compilation fails on Linux when NO_WEBVIEW is set to ON:

[ 64%] Building CXX object src/CMakeFiles/slade.dir/MainEditor/MainEditor.o
~/testuser/SLADE/src/MainEditor/MainEditor.cpp:98:43: error: 'void MainEditor::openDocs(string)' should have been declared inside 'MainEditor'
void MainEditor::openDocs(string page_name)
^
~/testuser/SLADE/src/MainEditor/MainEditor.cpp: In function 'void MainEditor::openDocs(string)':
/testuser/SLADE/src/MainEditor/MainEditor.cpp:100:15: error: 'class MainWindow' has no member named 'openDocs'
main_window->openDocs(page_name);

**Comment by Jacendi** [comment]
It was broken in #735
