### ISSUE TITLE
Fix the build on FreeBSD against Clang 6.0.1 and above

### ISSUE THREAD

**Issue by danfe** [sirjuddington/SLADE#989]
Recent versions of SLADE do not build on FreeBSD which uses Clang version 6.0.1 and above due to the following error:
```
src/MapEditor/UI/Dialogs/ActionSpecialDialog.cpp:692:69: error: constant expression evaluates to 2147483648 which cannot be narrowed to type 'long' [-Wc++11-narrowing]
        wxScrolled<wxPanel>{ parent, -1, wxDefaultPosition, wxDefaultSize, wxVSCROLL }
                                                                           ^~~~~~~~~
/usr/local/include/wx-3.0/wx/defs.h:1790:33: note: expanded from macro 'wxVSCROLL'
#define wxVSCROLL               0x80000000
                                ^~~~~~~~~~
src/MapEditor/UI/Dialogs/ActionSpecialDialog.cpp:692:69: note: insert an explicit cast to silence this issue
        wxScrolled<wxPanel>{ parent, -1, wxDefaultPosition, wxDefaultSize, wxVSCROLL }
                                                                           ^~~~~~~~~
                                                                           static_cast<long>( )
/usr/local/include/wx-3.0/wx/defs.h:1790:33: note: expanded from macro 'wxVSCROLL'
#define wxVSCROLL               0x80000000
                                ^~~~~~~~~~
1 error generated.
```
Spelling it as `static_cast<long>(wxVSCROLL)` fixes the problem.
